---
- name: Check if original file exists
  stat:
    path: "{{ config.dest }}"
  register: original

- set_fact:
    backup_required: "{{ original.stat.exists and not original.stat.islnk }}"

- debug:
    msg: "{{ config.dest }} exists; backup required"
  when: backup_required |bool

- name: Ensure backup directory exists
  file:
    path: "{{ backup_dir }}"
    state: directory
  when: backup_required |bool

- name: Backup file
  block:
    - name: Make copy of file
      copy:
        remote_src: yes
        src: "{{ config.dest }}"
        dest: "{{ backup_dir }}/"
        backup: yes # backupception
    - name: Remove original file
      file:
        path: "{{ config.dest }}"
        state: absent
  when: backup_required |bool

- name: Create symlink
  file:
    src: "{{ config.src }}"
    path: "{{ config.dest }}"
    state: link
