---
- hosts: localhost
  vars:
    config_base: "{{ playbook_dir }}"
    target_home: "/home/{{ target_user }}"
    xdg_config_home: "{{ target_user }}/.config"
  tasks:
    - name: install dotfile configuration
      include_tasks:
        file: install-config.yml
        apply:
          vars:
            config:
              src: "{{ config_base }}/{{ item.file }}"
              dest: "{{ target_home }}/.{{ item.file }}"
            backup_dir: "{{ target_home }}/.config-backup"
      loop:
        - { file: 'bash_profile' }
        - { file: 'bashrc' }
        - { file: 'dircolors' }
        - { file: 'gitconfig' }
        - { file: 'inputrc' }
        - { file: 'profile' }
        - { file: 'tmux.conf' }
        - { file: 'vimrc' }
        - { file: 'xinitrc' }
        - { file: 'xsession' }
    # TODO: Auto-create directory for configuration
    - name: install xdg dotfile configuration
      include_tasks:
        file: install-config.yml
        apply:
          vars:
            config:
              src: "{{ config_base }}/{{ item.file }}"
              dest: "{{ target_home }}/.config/{{ item.file }}"
            backup_dir: "{{ target_home }}/.config-backup"
      loop:
        - { file: 'awesome/rc.lua' }
