---
- hosts: localhost
  vars:
    config_base: "{{ playbook_dir }}"
    target_home: "/home/{{ target_user }}"
  tasks:
    - name: Install Dotfile Configuration
      include_tasks:
        file: install-config.yml
        apply:
          vars:
            config:
              src: "{{ config_base }}/{{ item.file }}"
              dest: "{{ target_home }}/.{{ item.file }}"
            backup_dir: "{{ target_home }}/.config-backup"
      loop:
        - { file: 'bashrc' }
