# #!/usr/bin/ksh


##
## Server options:
##    Set screen saver timeout to fifteen minutes.
##
#xset s 900 &

#[ -x /usr/bin/gnome-session ] &&  exec /usr/bin/gnome-session

## NOT remove the "+ut -ls" or *bad* things will happen!
#HOSTNAME=`hostname`
#exec xterm +ut -ls -name "@"$HOSTNAME -T "@"$HOSTNAME -n "@"$HOSTNAME
##
exec dwm/dwm
