[profile.files]
profile = "~/.profile"

[bash.files]
#TODO: Uncommenting causes error
#depends = ["profile"]
bashrc = "~/.bashrc"
bash_profile = "~/.bash_profile"
dircolors = "~/.dircolors"
inputrc = "~/.inputrc"

[git.files]
"gitconfig.hbs" = "~/.gitconfig"

[git.variables]
autocrlf = "input"
user.name = "Valentin Serrago"
user.email = "valentin.serrago@gmail.com"

[tealdeer.files]
"tealdeer/config.toml" = "~/.tealdeer/config.toml"

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[vim.files]
vimrc = "~/.vimrc"

[xresources.files]
Xresources = "~/.Xresources"

[xinitrc.files]
xinitrc = "~/.xinitrc"
